blueprint:
  name: "Set Media Player Volume"
  description: >
    This blueprint sets the volume of a specified media player.
  domain: script
  author: TheFes
  homeassistant:
    min_version: "2024.6.0"
  input:
    entity_id:
      name: "Media Player"
      description: "The media player to set the volume for."
      selector:
        entity:
          domain: media_player
    volume_level:
      name: "Volume Level"
      description: "The volume level to set (0.0 to 1.0)."
      selector:
        number:
          min: 0
          max: 1
          step: 0.01
          mode: slider
sequence:
  - service: media_player.volume_set
    target:
      entity_id: !input entity_id
    data:
      volume_level: !input volume_level
mode: parallel
icon: mdi:volume-high
